-- use testdatabase;
-- create table employees(
-- 	id int primary key auto_increment,
--     name varchar(100),
--     position varchar(100),
--     salary decimal(10,2)
-- );
-- insert into employees (id,name,position,salary)
-- value  (1,'혜린', 'PM' , 90000),
-- 	      (2, '은우','Frontend',80000),
-- 	      (3,'가을','Backend',92000),
--        (4,'지수','Frontend',78000),
--        (5,'민혁', 'Frontend', 96000),
--        (6,'하온','Backend',130000);

-- 모든 직원의 이름과 연봉 정보만을 조회하는 쿼리를 작성해주세요
-- select name, salary from employees;
-- 프론트엔드 직책을 가진 직원 중에 연봉이 90000 이하인 직원의 이름과 연봉을 조회하세요
-- select name, salary from employees where position = 'Frontend' and salary <= 90000;
-- pm 직책을 가진 모든 직원의 연봉을 10% 인상한후 그 결과를 확인하세요
--  set sql_safe_updates = 0; -- 세이프 모드가 되어있어서 에러가 발생 그것을 풀어준다
--  update employees
--  set salary = salary * 1.1
--  where position = 'PM';
-- select salary, name from employees where position = 'PM';
-- 모든 백엔드 직책을 가진 직원의 연봉을 5% 인상하세요
-- update employees
-- set salary = salary * 1.05
-- where position = 'Backend';
-- 민혁 사원의 데이터를 삭제하세요
-- delete from employees where name = '민혁';
-- 모든직원을 포지션 별로 그룹화하여 각 직책의 평균연봉을 계산하세요
-- select position, avg(salary) from employees group by position;  
-- 테이블을 삭제하세요
-- delete from employees --아까워서 못지우겠어요...